service: nodeless

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: sa-east-1
  memoreySize: 256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource: "arn:aws:s3:::nodeless/*" 

functions:
  optimize:
    handler: optimize.handle
    environment:
      BUCKET: brennoservelessimgupload
    events:
      - s3:
          bucket: brennoservelessimgupload
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
              suffix: .jpg
      - s3:
            bucket: brennoservelessimgupload
            event: s3:ObjectCreated:*
            rules:
              - prefix: uploads/
                suffix: .png
